
>P1;ORIG_SEQ
sequence::1    : :+667 : :undefined:undefined:-1.00:-1.00
MIHELLLALSGYPGSIFTWNKRSGLQVSQDFPFLHPSETSVLNRLCRLGTDYIRFTEFIEQYTGHVQQQDHHPSQ
QGQGGLHG*

>P1;PDB_SEQ
structureX:PDB_SEQ:   1 :A:+568 :A:MOL_ID  1; MOLECULE  GAMMA-TUBULIN COMPLEX COMPONENT 4; CHAIN  A; SYNONYM  GCP-4, HGCP4, GAMMA-RING COMPLEX PROTEIN 76 KDA, H HGRIP76; ENGINEERED  YES:MOL_ID  1; ORGANISM_SCIENTIFIC  HOMO SAPIENS; ORGANISM_COMMON  HUMAN; ORGANISM_TAXID  9606; GENE  TUBGCP4, 76P, GCP4; EXPRESSION_SYSTEM  ESCHERICHIA COLI; EXPRESSION_SYSTEM_TAXID  562; EXPRESSION_SYSTEM_STRAIN  ROSETTA(DE3)PLYSS; EXPRESSION_SYSTEM_VECTOR_TYPE  PLASMID; EXPRESSION_SYSTEM_PLASMID  PET26B (+): 2.30: 0.23
MIHELLLALSGYPGSIFTWNKRSGLQVSQDFPFLHPSETSVLNRLCRLGTDYIRFTEFIEQYTGH----------
---GGLHG*
