
>P1;GCP4_HUMAN
sequence::     : :     : :::-1.00:-1.00
----------------------------------------------------------MIHELLLALSGYPGSIF
TWNKR---------SGLQVSQDFPFLHPSETSVLNRLCRLGTDYIRFTEFIEQYTGHVQQQDHHPSQQGQGGLHG
*
>P1;GCP2_YEAST
sequence::     : :     : :::-1.00:-1.00
MEIKEVDDRAELLRYTNNIPLLGKLVNHQPLWSTNPKLKSFSLEKISAPDQRRVQEALVVKDLLNVLIGLEGTYI
RYFNDYEPSDPETPIEFKIAKKM---DPSFKTFSRRIVRYGKQYMILTRAYEKWSDT---------------SFG
*
