
>P1;GCP4_HUMAN
sequence::1    : :+568 : ::undefined:-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------MIHELLLALSGYPGSIFTWNKRSGLQVSQDFPFLHPSETSVL
NRLCRLGTDYIRFTEFIEQYTGHGGLHGIYLRAFCTGLDSVLQPYRQALLDLEQEFLGDPHLSISHVNYFLDQFQ
LLFPSVMVVVEQIKSQKIHGCQILETVYKHSCGGLPPVRSALEKILAVCHGVMYKQLSAWMLHGLLLDQHEEFFI
KQG-----------SLKQFSLRVEILPSYIPVRVAEKILFVGESVQMFEN-NVNLT-------SILKNQEDTFAA
ELHRLKQQPLFSLVDFEQVVDRIRSTVAEHLWKLMVEESDLLGQLKIIKDFYLLGRGELFQAFIDTAQHMLKTPP
TAVTEHDVNVAFQQSAHKVLLD-----DDNL--LPLLHLTIEYHG---ASGWAALGLSYKVQWPLHILFT---PA
VLEKYNVVFKYLLSVRRVQAELQHCWALQMQRKHLKS------------NQTDAIKWRLRNHMAFLVDNLQYYLQ
VDVLESQFSQLLHQINST-----------------------------------------------RDFESIRLAH
DHFLSNLLAQSFILL------------KPVFHCLNEILDLCHSFCSLVSQNL--L--------------DERGAA
Q----LSILVKGFSRQSSLLFKILSSVRNHQINSDLAQLLLRLDYNKYY*

>P1;GCP3_YEAST
sequence::1    : :+846 : ::undefined:-1.00:-1.00
MELEPTLFGIIEALAPQLLSQSHLQTFVSDVVNLLRSSTKSATQLGPLIDFYKLQSLDSPETTIMWHKIEKFLDA
LFGIQNTDDMVKYLSVFQSLLPSNYRAKIVQKSSGLNMENLANHEHLLSPVRAPSIYTEASFENMDRFSERRSMV
SSPNRYVPSSTYSSVTLRQLSNPYYVNTIPEEDILKYVSYTLLATTSALFPFDHE-QIQIPSKI---PNFESGLL
HLIFEAGLLYQSLGYKVEKFRML--NISPMKKALIIEISEELQNYTAFVNNLVSSG---TVVSLKSLYREIYENI
IRLRIYCRFTEHLEE--LSGDTFLIELNIFKSHGDLTIRKIATNLFNSMISLYYEYLMNWLTKGLLRATYGEFFI
AENTDTNGTDDDFIYHIPIEFNQERVPAFIPKELAYKIFMIGKSYIFLEKYCKEVQWTNEFSK----------KY
HVLYQSNSYRGISTNFFEIINDQYSEIVNHTNQILNQKFHYRDVVFALKNILLMGKSDFMDALIEKANDILATPS
DSLPNYKLTRVLQEAVQLSSLRHLMNSPRNSSVINGLDARVLDL-GHGSVGWDVFTLDYILYPPLSLVLNVNRPF
GRKEYLRIFNFLWRFKKNNYFYQKEMLKSNDIIRSFKKIRGYNPLIRDIINKLSRISILRTQFQQFNSKMESYYL
NCIIEENFKEMTRKLQRTENKSQNQFDLIRLNNGTIELNGILTPKAEVLTKSSSSKPQKHAIEKTLNIDELESVH
NTFLTNILSHKLFATNTSEISVGDYSGQPYPTSLVLLLNSVYEFVKVYCNLNDIGYEIFIKMNLNDHEASNGLLG
KFNTNLKEIVSQYKNFKDRLYIFRADLKNDG-DEELFLLSKSLR-----*
