
>P1;GCP4_HUMAN
sequence::1    : :+568 : ::undefined:-1.00:-1.00
MIHELLLALSGYPGSIFTWNKRSGLQVSQDFPFLHPSETSVLNRLCRLGTDYIRFTEFIEQYTGHGGLHGIYLRA
FCTGLDSVLQPYRQALLDLEQEFLGDPHLSISHVNYFLDQFQLLFPSVMVVVEQIKSQKIHGCQILETVYKHSCG
GLPPVRSALEKILAVCHGVMYKQLSAWMLHGLLLDQHEEFFIKQG-SLKQFSLRVEILPSYIPVRVAEKILFVGE
SVQMFEN-NVNLT-------SILKNQEDTFAAELHRLKQQPLFSLVDFEQVVDRIRSTVAEHLWKLMVEESDLLG
QLKIIKDFYLLGRGELFQAFIDTAQHMLKTPPTAVTEHDVNVAFQQSAHKVLLD-----DDNL--LPLLHLTIEY
HGASGWAALGLSYKVQWPLHILFT---PAVLEKYNVVFKYLLSVRRVQAELQHCWALQMQRKHLKS---------
---NQTDAIKWRLRNHMAFLVDNLQYYLQVDVLESQFSQLLHQINST-RDFESIRLAHDHFLSNLLAQSFILL--
----------KPVFHCLNEILDLCHSFCSLVSQNL--L--------------DERGAAQ----LSILVKGFSRQS
SLLFKILSSVRNHQINSDLAQLLLRLDYNKYY*

>P1;GCP3_YEAST
sequence::1    :A:+602 :D::undefined:-1.00:-1.00
ILKYVSYTLLATTSALFPFDHE-QIQIPSKI---PNFESGLLHLIFEAGLLYQSLGYKVEKFRML--NISPMKKA
LIIEISEELQNYTAFVNNLVSSG---TVVSLKSLYREIYENIIRLRIYCRFTEHLEE--LSGDTFLIELNIFKSH
GDLTIRKIATNLFNSMISLYYEYLMNWLTKGLLRATYGEFFIAEN/YHIPIEFNQERVPAFIPKELAYKIFMIGK
SYIFLEKYCKEVQWTNEFSK----------KYHVLYQSNSYRGISTNFFEIINDQYSEIVNHTNQILNQKFHYRD
VVFALKNILLMGKSDFMDALIEKANDILATPSDSLPNYKLTRVLQEAVQLSSLRHLMNSPRNSSVINGLDARVLD
L/SVGWDVFTLDYILYPPLSLVLNVNRPFGRKEYLRIFNFLWRFKKNNYFYQKEMLKSNDIIRSFKKIRGYNPLI
RDIINKLSRISILRTQFQQFNSKMESYYLNCIIEENFKEMTRKLQRT/LNIDELESVHNTFLTNILSHKLFATNT
SEISVGDYSGQPYPTSLVLLLNSVYEFVKVYCNLNDIGYEIFIKMNLNDHEASNGLLGKFNTNLKEIVSQYKNFK
DRLYIFRADLKNDG-DEELFLLSKSLR-----*
