
>P1;GCP4_HUMAN
structureX:gcp4:1    :A:+568 :A::MOL_ID  1; ORGANISM_SCIENTIFIC  HOMO SAPIENS; ORGANISM_COMMON  HUMAN; ORGANISM_TAXID  9606; GENE  TUBGCP4, 76P, GCP4; EXPRESSION_SYSTEM  ESCHERICHIA COLI; EXPRESSION_SYSTEM_TAXID  562; EXPRESSION_SYSTEM_STRAIN  ROSETTA(DE3)PLYSS; EXPRESSION_SYSTEM_VECTOR_TYPE  PLASMID; EXPRESSION_SYSTEM_PLASMID  PET26B (+): 2.30: 0.23
----MIHELLLALSGYPGSIFTWNKRSGLQVSQDFPFLHPSETSVLNRLCRLGTDYIRFTEFIEQYTGHGGLHGI
YLRAFCTGLDSVLQPYRQALLDLEQEFLGDPHLSISHVNYFLDQFQLLFPSVMVVVEQIKSQKIHGCQILETVYK
HSCGGLPPVRSALEKILAVCHGVMYKQLSAWMLHGLLLDQHEEFFIKQG-SLKQFSLRVEILPSYIPVRVAEKIL
FVGESVQMFEN-NVNLT-------SILKNQEDTFAAELHRLKQQPLFSLVDFEQVVDRIRSTVAEHLWKLMVEES
DLLGQLKIIKDFYLLGRGELFQAFIDTAQHMLKTPPTAVTEHDVNVAFQQSAHKVLLD-----DDNL--LPLLHL
TIEYHG---ASGWAALGLSYKVQWPLHILFT---PAVLEKYNVVFKYLLSVRRVQAELQHCWALQMQRKHLKSNQ
TDAIKWRLRNHMAFLVDNLQYYLQVDVLESQFSQLLHQINST-RDFESIRLAHDHFLSNLLAQSFILL-KPVFHC
LNEILDLCHSFCSLVSQNL--LDERGAAQ----LSILVKGFSRQSSLLFKILSSVRNHQINSDLAQLLLRLDYNK
YY*

>P1;GCP3_YEAST
sequence::1    :A:+565 :F::undefined:-1.00:-1.00
PEEDILKYVSYTLLATTSALFPFDHE-QIQIPSKI---PNFESGLLHLIFEAGLLYQSLGYKVEKFRML--NISP
MKKALIIEISEELQNYTAFVNNLVSSG---TVVSLKSLYREIYENIIRLRIYCRFTEHLEE--LSGDTFLIELNI
FKSHGDLTIRKIATNLFNSMISLYYEYLMNWLTKGLLRATYGEFFIAEN/YHIPIEFNQERVPAFIPKELAYKIF
MIGKSYIFLEKYCKEVQWTNEFSK----------KYHVLYQSNSYRGISTNFFEIINDQYSEIVNHTNQILNQKF
HYRDVVFALKNILLMGKSDFMDALIEKANDILATPSDSLPNYKLTRVLQEAVQLSSLRHLMNSPRNSSVINGLDA
RVLDL-GHGSVGWDVFTLDYILYPPLSLVLNVNRPFGRKEYLRIFNFLWRFKKNNYFYQKEMLKSNDIIR/--IN
KLSRISILRTQFQQFNSKMESYYLNCIIEENFKEMTRKLQRT/LNIDELESVHNTFLTNILSHKLFAT/QPYPTS
LVLLLNSVYEFVKVYCNLN/--SNGLLGKFNTNLKEIVSQYKNFKDRLYIFRADLKNDG-DEELFLLSKSLR---
--*
