
>P1;GCP4_HUMAN
structureX:gcp4_pos2:1    :A:+568 :A::MOL_ID  1; ORGANISM_SCIENTIFIC  HOMO SAPIENS; ORGANISM_COMMON  HUMAN; ORGANISM_TAXID  9606; GENE  TUBGCP4, 76P, GCP4; EXPRESSION_SYSTEM  ESCHERICHIA COLI; EXPRESSION_SYSTEM_TAXID  562; EXPRESSION_SYSTEM_STRAIN  ROSETTA(DE3)PLYSS; EXPRESSION_SYSTEM_VECTOR_TYPE  PLASMID; EXPRESSION_SYSTEM_PLASMID  PET26B (+): 2.30: 0.23
MIHELLLALSGYPGSIFTWNKRSGLQVSQDFPFLHPSETSVLNRLCRLGTDYIRFTEFIEQYTGHGGLHGIYLRA
FCTGLDSVLQPYRQALLDLEQEFLGDPHLSISHVNYFLDQFQLLFPSVMVVVEQIKSQKIHGCQILETVYKHSCG
GLPPVRSALEKILAVCHGVMYKQLSAWMLHGLLLDQHEEFFIKQG-SLKQFSLRVEILPSYIPVRVAEKILFVGE
SVQMFEN-NVNLTSILKNQEDTFAAELHRLKQQPLFSLVDFEQVVDRIRSTVAEHLWKLMVEESDLLGQLKIIKD
FYLLGRGELFQAFIDTAQHMLKTPPTAVTEHDVNVAFQQSAHKVLLD-----DDNL--LPLLHLTIEYHG---AS
GWAALGLSYKVQWPLHILFT---PAVLEKYNVVFKYLLSVRRVQAELQHCWALQMQRKHLKS-NQTDAIKWRLRN
HMAFLVDNLQYYLQVDVLESQFSQLLHQINST-RDFESIRLAHDHFLSNLLAQSFILL-KPVFHCLNEILDLCHS
FCSLVSQNL--L-DERGAAQ----LSILVKGFSRQSSLLFKILSSVRNHQINSDLAQLLLRLDYNKYY*

>P1;GCP3_YEAST
sequence::1    :A:+560 :G::undefined:-1.00:-1.00
ILKYVSYTLLATTSALFPFDHE-QIQIPSKI---PNFESGLLHLIFEAGLLYQSLGYKVEKFRML--NISPMKKA
LIIEISEELQNYTAFVNNLVSSG---TVVSLKSLYREIYENIIRLRIYCRFTEHLEE--LSGDTFLIELNIFKSH
GDLTIRKIATNLFNSMISLYYEYLMNWLTKGLLRATYGEFFIAEN/YHIPIEFNQERVPAFIPKELAYKIFMIGK
SYIFLEKYCKEVQ/---------KYHVLYQSNSYRGISTNFFEIINDQYSEIVNHTNQILNQKFHYRDVVFALKN
ILLMGKSDFMDALIEKANDILATPSDSLPNYKLTRVLQEAVQLSSLRHLMNSPRNSSVINGLDARVLDL-GHGSV
GWDVFTLDYILYPPLSLVLNVNRPFGRKEYLRIFNFLWRFKKNNYFYQKEMLKSNDIIRSFK/INKLSRISILRT
QFQQFNSKMESYYLNCIIEENFKEMTRKLQRT/LNIDELESVHNTFLTNILSHKLFAT/QPYPTSLVLLLNSVYE
FVKVYCNLNDIG/SNGLLGKFNTNLKEIVSQYKNFKDRLYIFRADLKNDG-DEELFLLSKSLR-----*
