
>P1;GCP4_HUMAN
structureX:gcp4_pos2:1    :A:+568 :A::MOL_ID  1; ORGANISM_SCIENTIFIC  HOMO SAPIENS; ORGANISM_COMMON  HUMAN; ORGANISM_TAXID  9606; GENE  TUBGCP4, 76P, GCP4; EXPRESSION_SYSTEM  ESCHERICHIA COLI; EXPRESSION_SYSTEM_TAXID  562; EXPRESSION_SYSTEM_STRAIN  ROSETTA(DE3)PLYSS; EXPRESSION_SYSTEM_VECTOR_TYPE  PLASMID; EXPRESSION_SYSTEM_PLASMID  PET26B (+): 2.30: 0.23
----MIHELLLALSGYPGSIFTWNKRSGLQVSQDFPFLHPSETSVLNRLCRLGTDYIRFTEFIEQYTGHGGLHGI
YLRAFCTGLDSVLQPYRQALLDLEQEFLGDPHLSISHVNYFLDQFQLLFPSVMVVVEQIKSQKIHGCQILETVYK
HSCGGLPPVRSALEKILAVCHGVMYKQLSAWMLHGLLLDQHEEFFIKQG-SLKQFSLRVEILPSYIPVRVAEKIL
FVGESVQMFEN-NVNLT-------SILKNQEDTFAAELHRLKQQPLFSLVDFEQVVDRIRSTVAEHLWKLMVEES
DLLGQLKIIKDFYLLGRGELFQAFIDTAQHMLKTPPTAVTEHDVNVAFQQSAHKVLLD-----DDNL--LPLLHL
TIEYHG---ASGWAALGLSYKVQWPLHILFT---PAVLEKYNVVFKYLLSVRRVQAELQHCWALQMQRKHLKS-N
QTDAIKWRLRNHMAFLVDNLQYYLQVDVLESQFSQLLHQINST-RDFESIRLAHDHFLSNLLAQSFILL------
------KPVFHCLNEILDLCHSFCSLVSQNL--L-DERGAAQ----LSILVKGFSRQSSLLFKILSSVRNHQINS
DLAQLLLRLDYNKYY*

>P1;GCP3_YEAST
sequence::1    :A:+583 :E::undefined:-1.00:-1.00
PEEDILKYVSYTLLATTSALFPFDHE-QIQIPSKI---PNFESGLLHLIFEAGLLYQSLGYKVEKFRML--NISP
MKKALIIEISEELQNYTAFVNNLVSSG---TVVSLKSLYREIYENIIRLRIYCRFTEHLEE--LSGDTFLIELNI
FKSHGDLTIRKIATNLFNSMISLYYEYLMNWLTKGLLRATYGEFFIAEN/YHIPIEFNQERVPAFIPKELAYKIF
MIGKSYIFLEKYCKEVQWTNEFSK----------KYHVLYQSNSYRGISTNFFEIINDQYSEIVNHTNQILNQKF
HYRDVVFALKNILLMGKSDFMDALIEKANDILATPSDSLPNYKLTRVLQEAVQLSSLRHLMNSPRNSSVINGLDA
RVLDL-GHGSVGWDVFTLDYILYPPLSLVLNVNRPFGRKEYLRIFNFLWRFKKNNYFYQKEMLKSNDIIRSFK/I
NKLSRISILRTQFQQFNSKMESYYLNCIIEENFKEMTRKLQRT/LNIDELESVHNTFLTNILSHKLFATNTSEIS
VGDYSGQPYPTSLVLLLNSVYEFVKVYCNLNDIG/SNGLLGKFNTNLKEIVSQYKNFKDRLYIFRADLKNDG-DE
ELFLLSKSLR-----*
