
>P1;GCP4_HUMAN
sequence::1    : :+667 : ::undefined:-1.00:-1.00
---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------MIHELLLALSGYPGSIFTWNKRSGLQVSQDFPFLHPSETSVL
NRLCRLGTDYIRFTEFIEQYTGHVQQQDHHPSQQGQGGLHGIYLRAFCTGLDSVLQPYRQALLDLEQEFLGDPHL
SISHVNYFLDQFQLLFPSVMVVVEQIKSQKIHGCQILETVYKHSCGGLPPVRSALEKILAVCHGVMYKQLSAWML
HGLLLDQHEEFFIKQGPSSGNVSAQPEEDEEDLGIGGLTGKQLRELQDLRLIEEENMLAPSLKQFSLRVEILPSY
IPVRVAEKILFVGESVQMFENQNVNLTRK-----GSILKNQEDTFAAELHRLKQQPLFSLVDFEQVVDRIRSTVA
EHLWKLMVEESDLLGQLKIIKDFYLLGRGELFQAFIDTAQHMLKTPPTAVTEHDVNVAFQQSAHKVLLD-----D
DNL--LPLLHLTIEYHGKEHKADATQAREGPSRETSPREAPASGWAALGLSYKVQWPLHILFT---PAVLEKYNV
VFKYLLSVRRVQAELQHCWALQMQRKHLKS------------NQTDAIKWRLRNHMAFLVDNLQYYLQVDVLESQ
FSQLLHQINST-----------------------------------------------RDFESIRLAHDHFLSNL
LAQSFILL------------KPVFHCLNEILDLCHSFCSLVSQNLGPL--------------DERGAAQ----LS
ILVKGFSRQSSLLFKILSSVRNHQINSDLAQLLLRLDYNKYYTQAGGTLGSFGM*

>P1;GCP3_YEAST
sequence::1    : :+846 : ::undefined:-1.00:-1.00
MELEPTLFGIIEALAPQLLSQSHLQTFVSDVVNLLRSSTKSATQLGPLIDFYKLQSLDSPETTIMWHKIEKFLDA
LFGIQNTDDMVKYLSVFQSLLPSNYRAKIVQKSSGLNMENLANHEHLLSPVRAPSIYTEASFENMDRFSERRSMV
SSPNRYVPSSTYSSVTLRQLSNPYYVNTIPEEDILKYVSYTLLATTSALFPFDHE-QIQIPSKI---PNFESGLL
HLIFEAGLLYQSLGYKVEKFRML---------------NISPMKKALIIEISEELQNYTAFVNNLVSSG---TVV
SLKSLYREIYENIIRLRIYCRFTEHLEE--LSGDTFLIELNIFKSHGDLTIRKIATNLFNSMISLYYEYLMNWLT
KGLLRATYGEFFIAENTDTNG---------------------------------TDDDFIYHIPIEFNQERVPAF
IPKELAYKIFMIGKSYIFLEKYCKEVQWTNEFSK-----------KYHVLYQSNSYRGISTNFFEIINDQYSEIV
NHTNQILNQKFHYRDVVFALKNILLMGKSDFMDALIEKANDILATPSDSLPNYKLTRVLQEAVQLSSLRHLMNSP
RNSSVINGLDARVLDL----------------------GHGSVGWDVFTLDYILYPPLSLVLNVNRPFGRKEYLR
IFNFLWRFKKNNYFYQKEMLKSNDIIRSFKKIRGYNPLIRDIINKLSRISILRTQFQQFNSKMESYYLNCIIEEN
FKEMTRKLQRTENKSQNQFDLIRLNNGTIELNGILTPKAEVLTKSSSSKPQKHAIEKTLNIDELESVHNTFLTNI
LSHKLFATNTSEISVGDYSGQPYPTSLVLLLNSVYEFVKVYCNLNDIGYEIFIKMNLNDHEASNGLLGKFNTNLK
EIVSQYKNFKDRLYIFRADLKNDG-DEELFLLSKSLR-----------------*
