
>P1;ORIG_SEQ
sequence::1    : :+451 : :undefined:undefined:-1.00:-1.00
MPREIITLQLGQCGNQIGFEFWKQLCAEHGISPEGIVEEFATEGTDRKDVFFYQADDEHYIPRAVLLDLEPRVIH
SILNSPYAKLYNPENIYLSEHGGGAGNNWASGFSQGEKIHEDIFDIIDREADGSDSLEGFVLCHSIAGGTGSGLG
SYLLERLNDRYPKKLVQTYSVFPNQDEMSDVVVQPYNSLLTLKRLTQNADCVVVLDNTALNRIATDRLHIQNPSF
SQINQLVSTIMSASTTTLRYPGYMNNDLIGLIASLIPTPRLHFLMTGYTPLTTDQSVASVRKTTVLDVMRRLLQP
KNVMVSTGRDRQTNHCYIAILNIIQGEVDPTQVHKSLQRIRERKLANFIPWGPASIQVALSRKSPYLPSAHRVSG
LMMANHTSISSLFERTCRQYDKLRKREAFLEQFRKEDMFKDNFDEMDTSREIVQQLIDEYHAATRPDYISWGTQE
Q*

>P1;PDB_SEQ
structureX:human_ytub_3CB2:   2 :A:+432 :A:MOL_ID  1; MOLECULE  TUBULIN GAMMA-1 CHAIN; CHAIN  A, B; SYNONYM  GAMMA-1-TUBULIN; GAMMA-TUBULIN COMPLEX COMPONENT 1; GCP-1; EC  3.6.5.6; ENGINEERED  YES:MOL_ID  1; ORGANISM_SCIENTIFIC  HOMO SAPIENS; ORGANISM_COMMON  HUMAN; GENE  TUBG1, TUBG; EXPRESSION_SYSTEM  SPODOPTERA FRUGIPERDA; EXPRESSION_SYSTEM_COMMON  FALL ARMYWORM; EXPRESSION_SYSTEM_STRAIN  SF9; EXPRESSION_SYSTEM_VECTOR_TYPE  BACULOVIRUS: 2.30: 0.19
-PREIITLQLGQCGNQIGFEFWKQLCAEHGISPEAIVEEFATEGTDRKDVFFYQADDEHYIPRAVLLDLEPRVIH
SILNSPYAKLYNPENIYLSEHGGGAGNNWASGFSQGEKIHEDIFDIIDREADGSDSLEGFVLCHSIAGGTGSGLG
SYLLERLNDRYPKKLVQTYSVFPNQDEMSDVVVQPYNSLLTLKRLTQNADCLVVLDNTALNRIATDRLHIQNPSF
SQINQLVSTIMSASTTTLRYPGYMNNDLIGLIASLIPTPRLHFLMTGYTPLT------SVRKTTVLDVMRRLLQP
KNVMVSTGRD--TNHCYIAILNIIQGEVDPTQVHKSLQRIRERKLANFIPWGPASIQVALSRKSPY-----RVSG
LMMANHTSISSLFERTCRQYDKLRKREAFLEQFRKEDMFKDNFDEMDTSREIVQQLIDEYHAATRPDYISW----
-*
