>P1;3rip_A
structureX:3rip_A: :A: :A:Gamma-tubulin complex component 4; helix bundles, gamma-tubulin ring complex, gamma-TURC, struc protein; 2.30A {Homo sapiens}:Homo sapiens:2.30:0.34
----------------------------------------------------------MIHELLLALSGYPGSIFTWNKR--------S-GLQVSQDFPF
LHPSETSVLNRLCRLGTDYIRFTEFIEQYTGH-GGLHGIYLRAFCTGLDSVLQP-YRQAL-LDLEQEFLGDPHLSISHVNYFLD--QFQLLFPSVMVVVE
QIKSQ-----------------------------------------KIHGCQILETVYKHSC--GGLPPVRSALEKILAVCHGVMYKQLSAWMLHGLLLD
QHEEFFIKQG---------------SLKQFSLRVEILPSYI----PVRVAEKILFVGESVQMFEN-NVN------LTSILKNQEDTFAAELHRLKQQPLF
SLVDFEQVVDRIRSTVAEHLWKLMVEESDLLGQLKII-KDFYLLGRGELFQAFIDTAQHMLKTPPTAVTEH---DVNVAFQQSAHKVLLDDDNLLPLLHL
TIEYH---------------------------------------------------------------GASGWAALGLSYKVQWPLHILFTPAVLEKYNV
VFKYLLSVRRVQAELQHCWALQMQR-----KHLKSNQTD-AIK--WRLRNHMAFLVDNLQYYLQVDVLESQFSQLLHQINSTRDFESIRLAHDHFLSNLL
AQSFILLKPVFHCLNEILDLCHSFCSLVSQ--------------------------------------NLLDERGA-------AQLSILVKGFSRQSSLL
FKILS---------SVRNHQINSDLAQLLL--RLD------*
>P1;Wed_Aug_12_07;05;24_+0200_2015
sequence:Wed_Aug_12_07;05;24_+0200_2015:   1: : 823: :: : 0.00: 0.00
MEIKEVDDRAELLRYTNNIPLLGKLVNHQPLWSTNPKLKSFSLEKISAPDQRRVQEALVVKDLLNVLIGLEGTYIRYFNDYEPSDPETPIEFKIAK---K
MDPSFKTFSRRIVRYGKQYMILTRAYEKWSDTS---FGMVLQRFAYEIRRFLEDVYLKTLVERLERDFNKVPNFSIRELEQIINETEVNKQMELLYNIYE
EIFREIEERRTNQSSQEDFNNFMDSMKNESSLHLRLMVAFDTTVYPVPKGGAILKIFQQKILENLGDRSSVMFLKKLLNNISQDYCTMLYEWLTQGILND
PYQEFMTYDDLEGKTDNIFDTRDRAWDTQYFIRKDVLLRDCDSEEDKNLLFKMLRTGILLKVVRASLQIPTIPSNSSDITIQEINDFAD---------LM
EGSNLELYVDKCYSRANEIFLKLFFQGYDLINVLKHLQQIFLGYQSGHNVLKFLTKNMGELTKHYRNDNNANYDKLLQNFELERQ-SENPNNLMRQLLMI
QFDTETLPQVLSHYLQIYPEVPENNSANDDSDPLMHANNFKNMNAILFDELSKERTGAYHGSNLELYTPKSAIYHLKFDINIPYPLNIIISRTCMIKYQI
ILRYQLVLQYHSRLLDETWMDLNKTPSWKYRGYSHTVKRRIVRATRVLHAKMNHFIKTIMEYFNQNVIDKEVYSLEKCYRNPTLAVAIQNELEGGLTNIM
TNRCLSD--LIPLQLQIFDIVYKFCKFIKSMRAKLCQLDPVLYEKHKSGMMKTLNEGYRTNNGGQEDVGYQEDAALELIQKLIEYISNASSIFRKCLINF
TQELSTEKFDFYDSSSVDAAGIERVLYSIVPPRSASASSQR*

