
>P1;GCP4_HUMAN
sequence::1    : :+568 : ::undefined:-1.00:-1.00
----MIHELLLALSGYPGSIFTWNKR---------SGLQVSQDFPFLHPSETSVLNRLCRLGTDYIRFTEFIEQY
TGHGGLHGIYLRAFCTGLDSVLQPYRQ--ALLDLEQEFLGDPHLSISHVNYFLDQFQL--LFPSVMVVVEQIKS-
-------QKIHGCQILETVYKHSCG--GLPPVRSALEKILAVCHGVMYKQLSAWMLHGLLLDQHEEFFIKQG-SL
KQFSLRVEILPSYI----PVRVAEKILFVGESVQMFEN-NVNLT-------SILKNQEDTFAAELHRLKQQPLFS
LVDFEQVVDRIRSTVAEHLWKLMVEESDLLGQLKIIKDFYLL-GRGELFQAFIDTAQHMLKTPPTAVTEHDVNVA
FQQSAHKVLLDDDNL--LPLLHLTIEYHG-ASGWAALGLSYKVQWPLHILFTPAVLEKYNVVFKYLLSVRRVQAE
LQHCWALQMQRKHLKS--------NQTDAIKWRLRNHMAFLVDNLQYYLQVDVLESQFSQLLHQINSTRDFESIR
LAHDHFLSNLLAQSFILLKPVFHCLNEILDLCHSFCSLVSQNL--L-DERGAAQLSILVKGFSRQSSLLFKILSS
VRNHQINSDLAQLLLRLDYN------KYY--------------*

>P1;GCP2_YEAST
sequence::1    :A:+621 :E::undefined:-1.00:-1.00
QEALVVKDLLNVLIGLEGTYIRYFNDYEPSDPETPIEFKIAKKM---DPSFKTFSRRIVRYGKQYMILTRAYEKW
SDT--SFGMVLQRFAYEIRRFLEDVYLKTLVERLERDFNKVPNFSIRELEQIINETEVNKQMELLYNIYEEIFRE
IEERRT/PVPKGGAILKIFQQKILENLGDRSSVMFLKKLLNNISQDYCTMLYEWLTQGILNDPYQEFMTYDD/WD
TQYFIRKDVLLRDCDSEEDKNLLFKMLRTGILLKVVRASLQIPTIPSNSSD----------ITIQEINDFADLME
GSNLELYVDKCYSRANEIFLKLFFQGYDLINVLKHLQQIFLGYQSGHNVLKFLTKNMGELTKHYRNDNNANYDKL
LQNFELERQSENPNNLMRQLLMIQFDTET/KSAIYHLKFDINIPYPLNIIISRTCMIKYQIILRYQLVLQYHSRL
LDETWMDLNKTPSWKYRGYSHTVKRRIVRATRVLHAKMNHFIKTIMEYFNQNVIDKEVYSLEKCYRNPTLAVAIQ
NELEGGLTNIMTNRCLS--DLIPLQLQIFDIVYKFCKFIKSMRAKL/EDAALELIQKLIEYISNASSIFRKCLIN
FTQEL-STEKFDFYDSSSVDAAGIERVLYSIVPPRSASASSQR*
