
>P1;GCP4_HUMAN
structureX:gcp4:1    :A:+568 :A::MOL_ID  1; ORGANISM_SCIENTIFIC  HOMO SAPIENS; ORGANISM_COMMON  HUMAN; ORGANISM_TAXID  9606; GENE  TUBGCP4, 76P, GCP4; EXPRESSION_SYSTEM  ESCHERICHIA COLI; EXPRESSION_SYSTEM_TAXID  562; EXPRESSION_SYSTEM_STRAIN  ROSETTA(DE3)PLYSS; EXPRESSION_SYSTEM_VECTOR_TYPE  PLASMID; EXPRESSION_SYSTEM_PLASMID  PET26B (+): 2.30: 0.23
----MIHELLLALSGYPGSIFTWNKR-SGLQVSQDFPFLHPSETSVLNRLCRLGTDYIRFTEFIEQYTGHGGLHG
IYLRAFCTGLDSVLQPYRQ--ALLDLEQEFLGDPHLSISHVNYFLDQFQL--LFPSVMVVVEQIKS--------Q
KIHGCQILETVYKHSCG--GLPPVRSALEKILAVCHGVMYKQLSAWMLHGLLLDQHEEFFIKQG-SLKQFSLRVE
ILPSYI----PVRVAEKILFVGESVQMFEN-NVNLT-------SILKNQEDTFAAELHRLKQQPLFSLVDFEQVV
DRIRSTVAEHLWKLMVEESDLLGQLKIIKDFYLL-GRGELFQAFIDTAQHMLKTPPTAVTEHDVNVAFQQSAHKV
LLDDDNL--LPLLHLTIEYHG-ASGWAALGLSYKVQWPLHILFTPAVLEKYNVVFKYLLSVRRVQAELQHCWALQ
MQRKHLKS-NQTDAIKWRLRNHMAFLVDNLQYYLQVDVLESQFSQLLHQINSTRDFESIRLAHDHFLSNLLAQSF
ILLKPVFHCLNEILDLCHSFCSLVSQNL--L-DERGAAQLSILVKGFSRQSSLLFKILSSVRNHQINSDLAQLLL
RLDYN*

>P1;GCP2_YEAST
sequence::1    :A:+581 :G::undefined:-1.00:-1.00
QEALVVKDLLNVLIGLEGTYIRYFND/IEFKIAKKM---DPSFKTFSRRIVRYGKQYMILTRAYEKWSDT--SFG
MVLQRFAYEIRRFLEDVYLKTLVERLERDFNKVPNFSIRELEQIINETEVNKQMELLYNIYEEIFREIEERRT/P
VPKGGAILKIFQQKILENLGDRSSVMFLKKLLNNISQDYCTMLYEWLTQGILNDPYQEFMTYDD/WDTQYFIRKD
VLLRDCDSEEDKNLLFKMLRTGILLKVVRASLQIPTIPSNSSD----------ITIQEINDFADLMEGSNLELYV
DKCYSRANEIFLKLFFQGYDLINVLKHLQQIFLGYQSGHNVLKFLTKNMGELTKHYRNDNNANYDKLLQNFELER
QSENPNNLMRQLLMIQFDTET/KSAIYHLKFDINIPYPLNIIISRTCMIKYQIILRYQLVLQYHSRLLDETWMDL
NKTPSWKY/RRIVRATRVLHAKMNHFIKTIMEYFNQNVIDKEVYSLEKCYRNPTLAVAIQNELEGGLTNIMTNRC
LS--DLIPLQLQIFDIVYKFCKFIKSMRAKL/EDAALELIQKLIEYISNASSIFRKCLINFTQEL-STEKFDFYD
SSSVD*
