
>P1;GCP4_HUMAN
structureX:gcp4_pos2:1    :A:+568 :A::MOL_ID  1; ORGANISM_SCIENTIFIC  HOMO SAPIENS; ORGANISM_COMMON  HUMAN; ORGANISM_TAXID  9606; GENE  TUBGCP4, 76P, GCP4; EXPRESSION_SYSTEM  ESCHERICHIA COLI; EXPRESSION_SYSTEM_TAXID  562; EXPRESSION_SYSTEM_STRAIN  ROSETTA(DE3)PLYSS; EXPRESSION_SYSTEM_VECTOR_TYPE  PLASMID; EXPRESSION_SYSTEM_PLASMID  PET26B (+): 2.30: 0.23
MIHELLLALSGYPGSIFTWNKR-SGLQVSQDFPFLHPSETSVLNRLCRLGTDYIRFTEFIEQYTGHGGLHGIYLR
AFCTGLDSVLQPYRQ--ALLDLEQEFLGDPHLSISHVNYFLDQFQL--LFPSVMVVVEQIKS-QKIHGCQILETV
YKHSCG--GLPPVRSALEKILAVCHGVMYKQLSAWMLHGLLLDQHEEFFIKQG---------SLKQFSLRVEILP
SYI----PVRVAEKILFVGESVQMFEN-NVNLTSILKNQEDTFAAELHRLKQQPLFSLVDFEQVVDRIRSTVAEH
LWKLMVEESDLLGQLKIIKDFYLL-GRGELFQAFIDTAQHMLKTPPTAVTEHDVNVAFQQSAHKVLLDDDNL--L
PLLHLTIEYHG-ASGWAALGLSYKVQWPLHILFTPAVLEKYNVVFKYLLSVRRVQAELQHCWALQMQRKHLKS-N
QTDAIKWRLRNHMAFLVDNLQYYLQVDVLESQFSQLLHQINSTRDFESIRLAHDHFLSNLLAQSFILLKPVFHCL
NEILDLCHSFCSLVSQNL--L-DERGAAQLSILVKGFSRQSSLLFKILSSVRNHQINSDLAQLLLRLDYN-KYY-*

>P1;GCP2_YEAST
sequence::1    :A:+574 :J::undefined:-1.00:-1.00
VVKDLLNVLIGLEGTYIRYFND/IEFKIAKKM---DPSFKTFSRRIVRYGKQYMILTRAYEKWSDT--SFGMVLQ
RFAYEIRRFLEDVYLKTLVERLERDFNKVPNFSIRELEQIINETEVNKQMELLYNIYEEIFR/PVPKGGAILKIF
QQKILENLGDRSSVMFLKKLLNNISQDYCTMLYEWLTQGILNDPYQEFMTYDDLEGKTDNI/WDTQYFIRKDVLL
RDCDSEEDKNLLFKMLRTGILLKVVRASLQIPT/---------ITIQEINDFADLMEGSNLELYVDKCYSRANEI
FLKLFFQGYDLINVLKHLQQIFLGYQSGHNVLKFLTKNMGELTKHYRNDNNANYDKLLQNFELERQSENPNNLMR
QLLMIQFDTET/KSAIYHLKFDINIPYPLNIIISRTCMIKYQIILRYQLVLQYHSRLLDETWMDLNKTPSWKY/R
RIVRATRVLHAKMNHFIKTIMEYFNQNVIDKEVYSLEKCYRNPTLAVAIQNELEGGLTNIMTNRCLS--DLIPLQ
LQIFDIVYKFCKFIKSMRAKL/EDAALELIQKLIEYISNASSIFRKCLINFTQEL-STEKFDFYDSSSVD/VLY/*
