
>P1;GCP4_HUMAN
structureX:gcp4:1    :A:+568 :A::MOL_ID  1; ORGANISM_SCIENTIFIC  HOMO SAPIENS; ORGANISM_COMMON  HUMAN; ORGANISM_TAXID  9606; GENE  TUBGCP4, 76P, GCP4; EXPRESSION_SYSTEM  ESCHERICHIA COLI; EXPRESSION_SYSTEM_TAXID  562; EXPRESSION_SYSTEM_STRAIN  ROSETTA(DE3)PLYSS; EXPRESSION_SYSTEM_VECTOR_TYPE  PLASMID; EXPRESSION_SYSTEM_PLASMID  PET26B (+): 2.30: 0.23
MIHELLLALSGYPGSIFTWNKR-SGLQVSQDFPFLHPSETSVLNRLCRLGTDYIRFTEFIEQYTGHGGLHGIYLR
AFCTGLDSVLQPYRQ--ALLDLEQEFLGDPHLSISHVNYFLDQFQL--LFPSVMVVVEQIKS-QKIHGCQILETV
YKHSCG--GLPPVRSALEKILAVCHGVMYKQLSAWMLHGLLLDQHEEFFIKQG-SLKQFSLRVEILPSYI----P
VRVAEKILFVGESVQMFEN-NVNLTSILKNQEDTFAAELHRLKQQPLFSLVDFEQVVDRIRSTVAEHLWKLMVEE
SDLLGQLKIIKDFYLL-GRGELFQAFIDTAQHMLKTPPTAVTEHDVNVAFQQSAHKVLLDDDNL--LPLLHLTIE
YHG-ASGWAALGLSYKVQWPLHILFTPAVLEKYNVVFKYLLSVRRVQAELQHCWALQMQRKHLKS-NQTDAIKWR
LRNHMAFLVDNLQYYLQVDVLESQFSQLLHQINSTRDFESIRLAHDHFLSNLLAQSFILLKPVFHCLNEILDLCH
SFCSLVSQNL--L-DERGAAQLSILVKGFSRQSSLLFKILSSVRNHQINSDLAQLLLRLDYN-KYY*

>P1;GCP2_YEAST
sequence::1    :A:+566 :I::undefined:-1.00:-1.00
VVKDLLNVLIGLEGTYIRYFND/IEFKIAKKM---DPSFKTFSRRIVRYGKQYMILTRAYEKWSDT--SFGMVLQ
RFAYEIRRFLEDVYLKTLVERLERDFNKVPNFSIRELEQIINETEVNKQMELLYNIYEEIFR/PVPKGGAILKIF
QQKILENLGDRSSVMFLKKLLNNISQDYCTMLYEWLTQGILNDPYQEFMTYDD/WDTQYFIRKDVLLRDCDSEED
KNLLFKMLRTGILLKVVRASLQIPT/---------ITIQEINDFADLMEGSNLELYVDKCYSRANEIFLKLFFQG
YDLINVLKHLQQIFLGYQSGHNVLKFLTKNMGELTKHYRNDNNANYDKLLQNFELERQSENPNNLMRQLLMIQFD
TET/KSAIYHLKFDINIPYPLNIIISRTCMIKYQIILRYQLVLQYHSRLLDETWMDLNKTPSWKY/RRIVRATRV
LHAKMNHFIKTIMEYFNQNVIDKEVYSLEKCYRNPTLAVAIQNELEGGLTNIMTNRCLS--DLIPLQLQIFDIVY
KFCKFIKSMRAKL/EDAALELIQKLIEYISNASSIFRKCLINFTQEL-STEKFDFYDSSSVD/VLY*
