
>P1;GCP4_HUMAN
sequence::1    : :+568 : ::undefined:-1.00:-1.00
----------------------------------------------------------MIHELLLALSGYPGSIF
TWNKR---------SGLQVSQDFPFLHPSETSVLNRLCRLGTDYIRFTEFIEQYTGHGGLHGIYLRAFCTGLDSV
LQPYRQ--ALLDLEQEFLGDPHLSISHVNYFLDQFQL--LFPSVMVVVEQIKS----------------------
-------------------QKIHGCQILETVYKHSCG--GLPPVRSALEKILAVCHGVMYKQLSAWMLHGLLLDQ
HEEFFIKQG---------------SLKQFSLRVEILPSYI----PVRVAEKILFVGESVQMFEN-NVNLT-----
--SILKNQEDTFAAELHRLKQQPLFSLVDFEQVVDRIRSTVAEHLWKLMVEESDLLGQLKIIKDFYLL-GRGELF
QAFIDTAQHMLKTPPTAVTEHDVNVAFQQSAHKVLLDDDNL--LPLLHLTIEYHG--------------------
-------------------------------------------ASGWAALGLSYKVQWPLHILFTPAVLEKYNVV
FKYLLSVRRVQAELQHCWALQMQRKHLKS--------NQTDAIKWRLRNHMAFLVDNLQYYLQVDVLESQFSQLL
HQINSTRDFESIRLAHDHFLSNLLAQSFILLKPVFHCLNEILDLCHSFCSLVSQNL--L----------------
--------------------DERGAAQLSILVKGFSRQSSLLFKILSSVRNHQINSDLAQLLLRLDYN------K
YY--------------*

>P1;GCP2_YEAST
sequence::1    : :+823 : ::undefined:-1.00:-1.00
MEIKEVDDRAELLRYTNNIPLLGKLVNHQPLWSTNPKLKSFSLEKISAPDQRRVQEALVVKDLLNVLIGLEGTYI
RYFNDYEPSDPETPIEFKIAKKM---DPSFKTFSRRIVRYGKQYMILTRAYEKWSDT--SFGMVLQRFAYEIRRF
LEDVYLKTLVERLERDFNKVPNFSIRELEQIINETEVNKQMELLYNIYEEIFREIEERRTNQSSQEDFNNFMDSM
KNESSLHLRLMVAFDTTVYPVPKGGAILKIFQQKILENLGDRSSVMFLKKLLNNISQDYCTMLYEWLTQGILNDP
YQEFMTYDDLEGKTDNIFDTRDRAWDTQYFIRKDVLLRDCDSEEDKNLLFKMLRTGILLKVVRASLQIPTIPSNS
SD----------ITIQEINDFADLMEGSNLELYVDKCYSRANEIFLKLFFQGYDLINVLKHLQQIFLGYQSGHNV
LKFLTKNMGELTKHYRNDNNANYDKLLQNFELERQSENPNNLMRQLLMIQFDTETLPQVLSHYLQIYPEVPENNS
ANDDSDPLMHANNFKNMNAILFDELSKERTGAYHGSNLELYTPKSAIYHLKFDINIPYPLNIIISRTCMIKYQII
LRYQLVLQYHSRLLDETWMDLNKTPSWKYRGYSHTVKRRIVRATRVLHAKMNHFIKTIMEYFNQNVIDKEVYSLE
KCYRNPTLAVAIQNELEGGLTNIMTNRCLS--DLIPLQLQIFDIVYKFCKFIKSMRAKLCQLDPVLYEKHKSGMM
KTLNEGYRTNNGGQEDVGYQEDAALELIQKLIEYISNASSIFRKCLINFTQEL-STEKFDFYDSSSVDAAGIERV
LYSIVPPRSASASSQR*
