
>P1;GCP4_HUMAN
sequence::1    : :+667 : ::undefined:-1.00:-1.00
----------------------------------------------------------MIHELLLALSGYPGSIF
TWNKR---------SGLQVSQDFPFLHPSETSVLNRLCRLGTDYIRFTEFIEQYTGHVQQQDHHPSQQGQGGLHG
IYLRAFCTGLDSVLQPYRQ--ALLDLEQEFLGDPHLSISHVNYFLDQFQL--LFPSVMVVVEQIKS---------
--------------------------------QKIHGCQILETVYKHSCG--GLPPVRSALEKILAVCHGVMYKQ
LSAWMLHGLLLDQHEEFFIKQGPSSGNVSAQPEEDEEDLGIGGLTGKQLRELQDLRLIEEENMLAPSLKQFSLRV
EILPSYI----PVRVAEKILFVGESVQMFENQNVNLTRK-----GSILKNQEDTFAAELHRLKQQPLFSLVDFEQ
VVDRIRSTVAEHLWKLMVEESDLLGQLKIIKDFYLL-GRGELFQAFIDTAQHMLKTPPTAVTEHDVNVAFQQSAH
KVLLDDDNL--LPLLHLTIEYHGKEHKADATQAREG---------------------------------------
PSRETSPREAPASGWAALGLSYKVQWPLHILFTPAVLEKYNVVFKYLLSVRRVQAELQHCWALQMQRKHLKS---
-----NQTDAIKWRLRNHMAFLVDNLQYYLQVDVLESQFSQLLHQINSTRDFESIRLAHDHFLSNLLAQSFILLK
PVFHCLNEILDLCHSFCSLVSQNLGPL------------------------------------DERGAAQLSILV
KGFSRQSSLLFKILSSVRNHQINSDLAQLLLRLDYN------KYYTQAGGTLG----SFGM*

>P1;GCP2_YEAST
sequence::1    : :+823 : ::undefined:-1.00:-1.00
MEIKEVDDRAELLRYTNNIPLLGKLVNHQPLWSTNPKLKSFSLEKISAPDQRRVQEALVVKDLLNVLIGLEGTYI
RYFNDYEPSDPETPIEFKIAKKM---DPSFKTFSRRIVRYGKQYMILTRAYEKWSDT---------------SFG
MVLQRFAYEIRRFLEDVYLKTLVERLERDFNKVPNFSIRELEQIINETEVNKQMELLYNIYEEIFREIEERRTNQ
SSQEDFNNFMDSMKNESSLHLRLMVAFDTTVYPVPKGGAILKIFQQKILENLGDRSSVMFLKKLLNNISQDYCTM
LYEWLTQGILNDPYQEFMTYDDLEGKT-DNI----------------------------FDTRDRAWDTQYFIRK
DVLLRDCDSEEDKNLLFKMLRTGILLKVVRASLQIPTIPSNSSD-----------ITIQEINDFADLMEGSNLEL
YVDKCYSRANEIFLKLFFQGYDLINVLKHLQQIFLGYQSGHNVLKFLTKNMGELTKHYRNDNNANYDKLLQNFEL
ERQSENPNNLMRQLLMIQFDTETLPQVLSHYLQIYPEVPENNSANDDSDPLMHANNFKNMNAILFDELSKERTGA
YHGSNLELYTPKSAIYHLKFDINIPYPLNIIISRTCMIKYQIILRYQLVLQYHSRLLDETWMDLNKTPSWKYRGY
SHTVKRRIVRATRVLHAKMNHFIKTIMEYFNQNVIDKEVYSLEKCYRNPTLAVAIQNELEGGLTNIMTNRCLS--
DLIPLQLQIFDIVYKFCKFIKSMRAKLCQLDPVLYEKHKSGMMKTLNEGYRTNNGGQEDVGYQEDAALELIQKLI
EYISNASSIFRKCLINFTQEL-STEKFDFYDSSSVDAAGIERVLYSIVPPRSASASSQR--*
